### ISSUE TITLE
The "edit" feature doesn't work properly when the "edited" tweet is a reply.

### ISSUE THREAD

**Issue by Leon422** [eramdam/BetterTweetDeck#302] opened 2017-12-31 19:44 UTC
Expected behaviour: The new tweet is a reply to the tweet the now-erased tweet was replying to.
Current behaviour: The new tweet is a reply to the now-erased tweet, therefore gives an error when trying to send it.

How to reproduce: Reply to a tweet, then try to "edit" the reply.

**Comment by FifoF** [comment] 2017-12-31 20:20
Seems to work fine for me.

**Comment by FifoF** [comment] 2017-12-31 20:37
I can’t reproduce it.

**Comment by Leon422** [comment] 2018-01-01 00:27
Weird, it works fine for me too now but it happened to me twice in a row before. Will try to get more details if it happens again (console data etc)

**Comment by EntranceJew** [comment] 2018-01-21 19:52
i investigated it when it was posted, but I couldn't reproduce it either
there are conditions for this to happen, such as:
 * chirp doesn't exist in any column any longer
 * chirp it is in response to does not exist in any column any longer, or never was
 * finding the base chirp from the pop-out modal no longer works 
 * the main TD account hit privacy issues when it resorted to using the API to get the main tweet back

**Comment by eramdam** [comment] 2018-01-23 05:43
Closing. Feel free to re-open if you re-reproduce.

**Closed by eramdam** 2018-01-23 05:43 UTC

**Comment by FifoF** [comment] 2018-01-23 08:35
Hmm, I’ve managed to get it several times. I still don’t know what causes it though.
