### ISSUE TITLE
BetterTweetDeck isn't loading after update

### ISSUE THREAD

**Issue by ThatsMiguel** [eramdam/BetterTweetDeck#351] opened 2018-06-25 11:38 UTC
![image](https://user-images.githubusercontent.com/29252011/41848212-0e7a04f4-7853-11e8-9238-144caa451964.png)
![image](https://user-images.githubusercontent.com/29252011/41848231-1e3af1be-7853-11e8-95f4-31d63ebaea3e.png)

It's not applying any change that i've made

**Comment by eramdam** [comment] 2018-06-25 14:33
Duplicate of https://github.com/eramdam/BetterTweetDeck/issues/350

A fix is on the way.

**Closed by eramdam** 2018-06-25 14:33 UTC
Labels: duplicate
