### ISSUE TITLE
Smaller column width cuts off more options menu with quote tweets

### ISSUE THREAD

**Issue by nymphlode** [eramdam/BetterTweetDeck#568] opened 2021-04-07 03:00 UTC
**Describe the bug**
When using the "more options" three dot menu when viewing the tweet within a quoted tweet, it will cut off the drop down menu on the left side.

**To Reproduce**
1. Set "custom width for columns" to 264px. Save and refresh TweetDeck.
2. Go to a tweet that has been quoted by you or someone else.
3. Click on the original tweet within that quote to view it.
4. Click on "more info" three dot menu.
5. See menu is cut off.

**Expected behavior**
The menu opens as is not cut off on the left side.

**Screenshots**
![tweetdeckbugreporrt](https://user-images.githubusercontent.com/11083026/113803839-33d90c00-9712-11eb-9aeb-8e54d1397d05.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Brave
 - Version: 1.22.71

**Comment by eramdam** [comment] 2021-04-07 05:38
Duplicate of https://github.com/eramdam/BetterTweetDeck/issues/544

**Closed by eramdam** 2021-04-07 05:38 UTC
Labels: bug
