### ISSUE TITLE
[Feature Request] Custom grid layout

### ISSUE THREAD

**Issue by viksra** [eramdam/BetterTweetDeck#660] opened 2021-08-02 20:41 UTC
Just as you can select a table layout in Microsoft Word, it would be nice if you could insert a custom table into TweetDeck. https://i.imgur.com/ixwl65k.png This way you can drag and drop different twitter profiles into different rows. 

It would effectively be the same as stacking two browser windows on top of each other, but contained within one window.

**Comment by eramdam** [comment] 2021-08-02 20:50
Duplicate of https://github.com/eramdam/BetterTweetDeck/issues/377

**Closed by eramdam** 2021-08-02 20:50 UTC
