### ISSUE TITLE
Add a clear button to clear all the tabs at once

### ISSUE THREAD

**Issue by flinterwood** [eramdam/BetterTweetDeck#603] opened 2021-04-25 04:57 UTC
i have tons of columns on tweetdeck and it's kind annoying clear one by one all the time. it would help me and save a lot of time if i could clear all of them at once

**Comment by eramdam** [comment] 2021-05-15 22:25
Duplicate of https://github.com/eramdam/BetterTweetDeck/issues/471

**Closed by eramdam** 2021-05-15 22:25 UTC
Labels: feature
