### ISSUE TITLE
Adding GIFs to tweet is broken

### ISSUE THREAD

**Issue by BrosephJ** [eramdam/BetterTweetDeck#475] opened 2020-05-13 15:30 UTC
![firefox_2020-05-13_08-27-43](https://user-images.githubusercontent.com/5185864/81832888-e2210500-94f3-11ea-9163-bb37e8afcc30.png)

Firefox 77.0b5

**Comment by eramdam** [comment] 2020-05-13 20:28
Works here (although im on Firefox 76). Make sure you dont have an extension such as uBlock/Ghostery that could be enabled on TweetDeck. I've heard several reports and every time that kind of extension was the culprit.

**Comment by BigGunnLP** [comment] 2020-05-21 21:12
Happening on the latest Chrome (Version 83.0.4103.61 (Official Build) (64-bit)) now as well. Also I've noticed the stock gif button is missing when replying to tweets in Tweetdeck even in an instance of the browser with zero extensions added.

**Comment by eramdam** [comment] 2020-05-21 21:50
Works fine here on Chrome 🤷 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/1409924/82609900-4ab25680-9b72-11ea-89d3-365af38678f9.png">

@BigGunnLP are you sure you dont have any extension like Ghostery/Adblock that would interfer with Better TweetDeck somehow?

**Comment by BigGunnLP** [comment] 2020-05-22 20:08
Tweeten was installed and I didn't see it. That was causing the conflict.

**Comment by eramdam** [comment] 2020-05-22 20:12
I'll close the issue. Since OP reported on a beta version of Firefox, I'd rather wait until the stable release of 77 happens to see if it's still an issue and re-open it if necessary.

**Comment by eramdam** [comment] 2020-05-25 05:25
I've confirmed that this is still an issue on Firefox 77beta9. I've opened a PR with a fix. I'll merge it if it's still an issue once Firefox 77 gets released

https://github.com/eramdam/BetterTweetDeck/pull/481

**Comment by eramdam** [comment] 2020-06-02 16:14
So I just received Firefox 77 and as far as I can tell the addition of GIFs work just fine so I'll close this issue.

**Closed by eramdam** 2020-06-02 16:14 UTC

**Comment by Athanasius** [comment] 2020-06-09 13:24
I'm on FF 77.0.1 and seeing this issue.  In the console I'm seeing:

`Content Security Policy: The page's settings blocked the loading of a resource at https://api.giphy.com/v1/gifs/trending?api_key=l6yX6p85ZhD7tPc2MvUBSEAPXOqXg1dL&limit=10 ("connect-src").`

which might be related ?  I've disabled all the following for tweetdeck: uMatrix, uBlock Origin, Privacy Badger.

**Comment by Athanasius** [comment] 2020-06-09 13:38
To add to the above, this is on Windows 10 (not 2004, the version before).  I've also now tried with the following completely disabled (rather than just whitelisting both tweetdeck.twitter.com and twitter.com): uBlock Origin, uMatrix, Privacy Badger, TamperMonkey, Stylus.   The problem persists.

My specific test case is:

1) Spot a tweet I want to reply to with a GIF
2) Click Reply
3) Click 'pop out' to get it in the side bar
4) Click the 'GIF' icon
5) Observe no pre-loading of GIFs
6) Type some search text and hit return
7) Observe still no GIFs shown.

And as above, that CSP error in the console.

**Comment by eramdam** [comment] 2020-06-09 16:17
@Athanasius are you sure you're running the latest version of the extension (3.9.15)? Because it should be fixed 🤔

**Comment by Athanasius** [comment] 2020-06-09 16:19
Ah yes, I am still somehow only on 3.9.14, I shall poke at things to upgrade and retest.

**Comment by Athanasius** [comment] 2020-06-09 16:21
Yup, all good on 3.9.15.  I shall now glare at FF for not auto updating, given it did so fine with a manual 'check for updates'.

**Comment by eramdam** [comment] 2020-06-09 16:37
@Athanasius I had to add new permissions in the .15 update so I think Firefox blocks the auto-upgrade until you confirm it (usually it shows a ⚠️ icon on top of the menu icon in the toolbar to signify that)

**Comment by Athanasius** [comment] 2020-06-09 16:41
I've noticed that icon in the past, but definitely hadn't seen it for this.  Anyway, sorted now, sorry for the noise.  Keep up the great work!
