### ISSUE TITLE
Re-requesting notification perms

### ISSUE THREAD

**Issue by tombh** [eramdam/BetterTweetDeck#29] opened 2015-02-24 11:34 UTC
Would you be interested in a PR to re-request notification perms?

Really this is something that Tweetdeck themselves should sort out (ha, but the same could be said for the whole of BetterTweetDeck!): whenever I use Tweetdeck on a new browser notifications stop working because Tweetdeck don't check `window.Notification.permission` :( Once perms have been granted they assume your good for life.

To be fair there is a quick fix by just pasting `window.Notification.requestPermission()` into the JS console.

BTW awesome work on this, I love it. Also it works perfectly in Opera :D

**Comment by nullr1ver** [comment] 2015-04-12 13:34
THIS \^^^

**Comment by nullr1ver** [comment] 2015-04-12 13:34
Not a bad idea

**Comment by tombh** [comment] 2015-04-12 14:56
Will it get merged though?

**Comment by eramdam** [comment] 2015-12-27 03:22
I will look at it when developing 3.0. I just hope there won't be somekind of sandboxing issues because it sounds typically like something that could be sandboxed :)

**Comment by eramdam** [comment] 2016-09-02 05:33
@tombh I just re-tried and it seems like TweetDeck is now smart enough to display a banner when it lost notifications permissions? Can you confirm ?

**Comment by eramdam** [comment] 2017-02-04 00:35
Closing this until confirmed really needed

**Closed by eramdam** 2017-02-04 00:35 UTC
Labels: feature
