### ISSUE TITLE
Columns vertically offset

### ISSUE THREAD

**Issue by noamross** [eramdam/BetterTweetDeck#450] opened 2019-11-01 20:09 UTC
Pretty frequently I encounter a bug where some columns are offset vertically down, like so:

<img width="1332" alt="Screenshot 2019-11-01 13 27 44" src="https://user-images.githubusercontent.com/571752/68043450-b5ba3f80-fcab-11e9-978f-63a0ff8bec7f.png">

I've yet to figure out what triggers this.  It generally goes away when the screen is refreshed. I've attempted to find the reason via Chrome Devtools Inspector. All I've got so far is that modifying the document properties has a similar effect to refreshing the page, so it seems to be introduced in some intermittent (flexbox?) page calculation. Happy to look more when the behavior pops up if you have suggestions as to what to look at.

**Comment by rmzab** [comment] 2020-05-31 03:51
I can't figure it out as well. From the best I can tell it is still occurring, though I am seeing it in Edge. It appears most often when opening an embedded tweet with media. Clicking the "Back to Column" button at the top either reproduces the issue or it simply resets all columns that are offset.

**Comment by eramdam** [comment] 2020-06-11 23:48
I've got the confirmation that this is a regression in Blink and will get fixed in Chrome 85

https://twitter.com/bfgeek/status/1271222802545209344
https://twitter.com/bfgeek/status/1271224333843566592

I'll try to implement a work around since there's an easy way to reproduce now but I can't promise anything.

**Comment by eramdam** [comment] 2020-06-16 17:21
Chrome 84 (planned for ~14th of July) will fix that issue, fwiw https://bugs.chromium.org/p/chromium/issues/detail?id=1088340#c20

**Comment by eramdam** [comment] 2020-07-15 15:49
This has been fixed in Chromium 84.

**Closed by eramdam** 2020-07-15 15:49 UTC
