### ISSUE TITLE
Dark/Light mode disappeared on Desktop Tweetdeck + themes button doesn't work

### ISSUE THREAD

**Issue by dukefolk** [eramdam/BetterTweetDeck#580] opened 2021-04-10 09:31 UTC
On the desktop version the dark/light mode button has been removed and replaced with a themes button that actually doesn't work. When I click on it it won't do anything so I'm stuck to dark mode by default.

**Comment by eramdam** [comment] 2021-04-10 15:56
What browser are you using? This would be really useful in order to know what’s going on. @dukefolk

**Comment by dukefolk** [comment] 2021-04-11 10:38
Hi,

I am using Chrome

**Comment by eramdam** [comment] 2021-04-12 04:25
I can't reproduce on Chrome, the link works fine for me... perhaps Chrome is blocking the opening of the window somehow?

**Comment by eramdam** [comment] 2021-04-12 16:23
Fixed in 4.0.3

**Closed by eramdam** 2021-04-12 16:23 UTC
Labels: bug
