### ISSUE TITLE
Update notification plays every time Opera is reopened

### ISSUE THREAD

**Issue by tripl3dogdare** [eramdam/BetterTweetDeck#171] opened 2017-06-19 15:53 UTC
**Expected behavior:** Update notification plays once, then goes away.

**Actual behavior:** Update notification plays every time Opera is closed and reopened.

**Steps to reproduce:**
1. Open Opera
2. Note upgrade notification
3. Close Opera
4. Open Opera
5. Note upgrade notification again

This problem persists even if you click the notification to go see the changelog.
It is very possible that this problem exists in other browsers, but I cannot confirm.

**Affected versions:** 3.3.9

**Comment by eramdam** [comment] 2017-06-19 17:36
@tripl3dogdare Hum, I can't reproduce this on Chrome. Can you check in the settings in the debug what value has the `need_update_banner` preference, if it's even defined? I guess you installed the version from the Opera store directly?

**Comment by tripl3dogdare** [comment] 2017-06-19 17:40
Yes, I installed it from the Opera store.

I don't really know my way around Opera yet, could you point me in the right direction as to how to access that value? If you can, I'd be more than happy to.

**Comment by eramdam** [comment] 2017-06-19 18:08
@tripl3dogdare 

1. Open the settings of the extension, by clicking on that blue icon in the TweetDeck's UI 
![image](https://user-images.githubusercontent.com/1409924/27298936-7089a1c4-54df-11e7-9626-6bb45b823a9f.png)
2. Open the  "debug infos" section 
![image](https://user-images.githubusercontent.com/1409924/27298951-80d8609c-54df-11e7-8d0d-24fca94e07e7.png)
3. Look for `need_update_banner` in the code block 
![image](https://user-images.githubusercontent.com/1409924/27298978-91c5f888-54df-11e7-823a-024bea36bed2.png)

**Comment by tripl3dogdare** [comment] 2017-06-19 18:11
"need_update_banner": false, just as expected, so the bug isn't with however you store that it's been shown.

It may also be worth noting that the banner at the top of Tweetdeck's site stays dismissed, but the desktop notification does not.

**Comment by eramdam** [comment] 2017-06-19 18:30
@tripl3dogdare oh! I thought you were talking about the TweetDeck's-like banner. I guess a restart of Opera didn't change much?

**Comment by tripl3dogdare** [comment] 2017-06-19 18:39
Nope. Restarting Opera is a part of the steps to reproduce.

**Comment by eramdam** [comment] 2017-06-19 19:54
@tripl3dogdare ok. Unfortunately I never use Opera so I can't put myself in a state where the extension is being updated so it will be hard for me to debug this. I'll try to investigate though. As a (dirty) work-around, you could use this https://addons.opera.com/en/extensions/details/download-chrome-extension-9/ and install the Chrome version which hopefully doesn't trigger the issue 🤔

**Comment by tripl3dogdare** [comment] 2017-06-19 20:13
Thanks =)

**Comment by eramdam** [comment] 2017-06-22 04:37
@tripl3dogdare I just happened to have an Opera setup w/ BTD installed from the Opera Store, it updated itself and the update banner showed only once. So I definitely don't know why you could encounter this bug 😞

**Comment by tripl3dogdare** [comment] 2017-06-22 04:41
Oddly enough, the issue seems to have disappeared. Not sure how. Is it possible that the desktop notification keeps playing until the on-site banner is dismissed?

**Comment by eramdam** [comment] 2017-06-22 04:50
@tripl3dogdare the desktop notification is supposed to play only once :/

**Comment by tripl3dogdare** [comment] 2017-06-22 04:56
Whiiiiich it didn't - it played over and over again until (and this is the only thing I can think of, not entirely sure) I went to the site and dismissed the update banner there.

**Comment by eramdam** [comment] 2017-06-25 18:19
I'm closing this as the last releases don't open desktop notifications anymore.

**Closed by eramdam** 2017-06-25 18:19 UTC
