### ISSUE TITLE
Stuck in Dark Mode

### ISSUE THREAD

**Issue by jewels667** [eramdam/BetterTweetDeck#584] opened 2021-04-12 02:51 UTC
Several times since the update TweetDeck has flipped to dark mode on its own after a refresh. Now it no longer gives me the option to select light mode. Under Theme it says "select theme preferences" on what looks like a hyperlink. Dark/Light ticky box no longer available. When you click the text, nothing happens. I am using Chrome.

**Comment by eramdam** [comment] 2021-04-12 04:41
Duplicate of https://github.com/eramdam/BetterTweetDeck/issues/580

**Closed by eramdam** 2021-04-12 04:41 UTC
Labels: bug

**Comment by eramdam** [comment] 2021-04-12 16:25
Fixed in 4.0.3
