### ISSUE TITLE
Scrolling on Card in column

### ISSUE THREAD

**Issue by tomocrafter** [eramdam/BetterTweetDeck#538] opened 2021-04-04 17:29 UTC
When scrolling with mouse on card in column results in makes scrolling slower/smoother, but not on it then it will be normal scrolling.
This makes users uncomfortable when scrolling over timelines.

Confirmed on V4 Beta, and latest stable V4.

**Comment by eramdam** [comment] 2021-04-04 17:39
I'm really not sure I understand the issue.. Can you maybe record the screen when the issue happens?

**Comment by tomocrafter** [comment] 2021-04-05 01:39
https://user-images.githubusercontent.com/10905364/113528310-2a10b500-95fb-11eb-901d-7cc361fec47b.mp4

Sorry for weird resolution.

**Comment by eramdam** [comment] 2021-04-05 03:03
Hum, my guess is that the cards loading briefly interrupt the scroll since suddenly the content of tweets takes more vertical space. I'll look at this at some point but I can't make promises given how much of an edge case this is (I haven't noticed that when my columns dont have a lot of cards..).

**Comment by tomocrafter** [comment] 2021-04-05 03:37
It does occurs when not scrolling that needs load. Like this.
The iframe is causing this problem imo.

https://user-images.githubusercontent.com/10905364/113534390-985d7380-960b-11eb-8997-bd5a2a9d766e.mp4

**Comment by eramdam** [comment] 2021-04-05 04:02
I mean, yeah, but that's how the cards work, they render as iframes, there's nothing I can do. What browser is that, however? Because I can't reproduce on Firefox.

**Comment by tomocrafter** [comment] 2021-04-05 04:05
I'm using brave browser that based on chromium.

**Comment by eramdam** [comment] 2021-04-05 04:30
I'll try on Chrome/Edge. I do not officially support Brave.

**Comment by eramdam** [comment] 2021-04-05 05:05
I can't repro on Chrome. Although i have an external mouse, do you by any chance use a trackpad? I'm trying to figure out the differences between our setups, although I'd suspect Brave has some differences in the way it handles the scroll behavior (or maybe its anti-tracking protection messes up something when the cards iframe load?)

**Comment by eramdam** [comment] 2021-04-06 18:46
I'm closing this and going to assume it's something Brave-specific unless somebody comes up with a similar report on a non-Brave browser.

**Closed by eramdam** 2021-04-06 18:46 UTC
Labels: bug

**Comment by tomocrafter** [comment] 2021-07-31 06:34
I'm sorry to replying to closed issue.
I have no idea but this issue has solved with version 4.4.0, thanks!
