### ISSUE TITLE
Videos use the HTML5 player instead of the normal Twitter player.

### ISSUE THREAD

**Issue by archeruwu** [eramdam/BetterTweetDeck#478] opened 2020-05-20 01:39 UTC
When clicking on a Video or a Tweet with a video, it uses the HTML5 player instead of the Twitter player, even after the 3.9.11 update that said to fix it.

![image](https://user-images.githubusercontent.com/18449883/82395222-0e1f1780-9a19-11ea-8eb2-1b18bb7f912f.png)

Browser: Firefox Quantum 76.0.1 64bit

**Comment by archeruwu** [comment] 2020-05-20 16:45
Update to this:

I was looking at other issues on the Issues tab, and have tried disabling Tampermonkey;
Doesn't fix it.

And I have also noticed, opening Images as well as Videos prevents the actions bar from being used.
![image](https://user-images.githubusercontent.com/18449883/82473546-bd023880-9a97-11ea-855b-aa6ffda09521.png)

**Comment by eramdam** [comment] 2020-05-20 18:16
The update only fixed a specific interaction with the modal while having the "No background behind modal" setting enabled. it was never intended to bring back the old Twitter video player.

> And I have also noticed, opening Images as well as Videos prevents the actions bar from being used.

Yes, this is a regression i shipped while trying to fix the underlying issue. I am in the process on working around this and preparing a release to fix it once and for all.

**Comment by eramdam** [comment] 2020-05-24 05:05
> The update only fixed a specific interaction with the modal while having the "No background behind modal" setting enabled. it was never intended to bring back the old Twitter video player.
> 
> > And I have also noticed, opening Images as well as Videos prevents the actions bar from being used.
> 
> Yes, this is a regression i shipped while trying to fix the underlying issue. I am in the process on working around this and preparing a release to fix it once and for all.

The pointer thing should be fixed in 3.9.13 that I just published. Closing the issue as I don't intend to revert TweetDeck's decision of switching to a HTML5 video player.

**Closed by eramdam** 2020-05-24 05:05 UTC
