### ISSUE TITLE
DM'ing adding picture bug (Blue background pop-up instead of DM UX/UI)

### ISSUE THREAD

**Issue by Majinmind** [eramdam/BetterTweetDeck#602] opened 2021-04-24 20:21 UTC
**Describe the bug**

**To Reproduce**
1. Go to any profile's DMs
2. Ctrl + V an image to the DMs
3. Pop-up on left is blue

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by eramdam** [comment] 2021-04-24 20:30
Sounds like a duplicate of https://github.com/eramdam/BetterTweetDeck/issues/600, which will be fixed in the next release.

**Closed by eramdam** 2021-04-24 20:30 UTC
Labels: bug

**Comment by hiroto7** [comment] 2021-04-24 21:39
I tried to reproduce the bug, and I have found that it still occurs.
But it seems to be due to a bug of not BTD but the original TD because even when the BTD extension is disabled, clicking a 'popout' button below any textbox in DM causes the same thing.
